---
name: "base"

on:
  pull_request:
    paths:
    - 'base/**'

jobs:
  base:
    runs-on: "ubuntu-20.04"
    strategy:
      matrix:
        variant: ["minimal", "nodoc", "full"]
        release: ["stable", "testing", "unstable"]
    steps:
    - uses: "actions/checkout@v2"
    - name: "install dependencies"
      run: |
        sudo bash -c '
          apt-get update
          apt-get install -qy debootstrap
        '
    - name: "create rootfs"
      run: |
        sudo bash -c '
          ./base/create_rootfs.sh --variant ${{ matrix.variant }} --release ${{ matrix.release }} "$(mktemp -d)"
        '
