---
name: "ci"

on:
  push: {}
  pull_request: {}

jobs:
  minimal:
    runs-on: "ubuntu-20.04"
    strategy:
      matrix:
        release: ["stable", "testing", "unstable", "sid"]
    steps:
    - uses: "actions/checkout@v2"
    - name: "install dependencies"
      run: |
        sudo -E bash -c '
          apt-get update
          apt-get install -qy debootstrap
        '
    - name: "create rootfs"
      env:
        RELEASE: "${{ matrix.release }}"
      run: |
        sudo -E bash -c '
          ./minimal/create_rootfs.sh "$(mktemp -d)"
        '

  static-code-analysis:
    runs-on: "ubuntu-20.04"
    steps:
    - uses: "actions/checkout@v2"
    - name: "install dependencies"
      run: |
        sudo -E bash -c '
          curl -sSLf https://github.com/mvdan/sh/releases/download/v3.4.0/shfmt_v3.4.0_linux_amd64 >/usr/local/bin/shfmt
          curl -sSLf https://github.com/koalaman/shellcheck/releases/download/v0.7.2/shellcheck-v0.7.2.linux.x86_64.tar.xz | tar -Jx shellcheck-v0.7.2/shellcheck --to-stdout >/usr/local/bin/shellcheck
          chmod 0755 /usr/local/bin/*
        '
    - name: "run static code analysis"
      run: |
        shellcheck --enable=all --severity=style --check-sourced --external-sources --source-path=SCRIPTDIR $(find . -name '*.sh')
        shfmt -d -i 2 -bn -ci $(find . -name '*.sh')
