---
name: "publish-images"

on:
  schedule:
  - cron: '0 0 * * *'

jobs:
  minimal:
    runs-on: "ubuntu-20.04"
    strategy:
      matrix:
        variant: ["full"]
        release: ["testing"]
    steps:
    - uses: "actions/checkout@v2"
    - name: "install dependencies"
      run: |
        sudo bash -c '
          apt-get update
          apt-get install -qy debootstrap
        '
    - name: "build"
      run: |
        sudo bash -c '
          dir=$(mktemp -d)
          ./base/create_rootfs.sh --variant ${{ matrix.variant }} --release ${{ matrix.release }} "${dir}"
          tar -cpC "${dir}" . | docker import --change "ENTRYPOINT []" --change "CMD [\"/bin/bash\"]" - "ghcr.io/szubersk/debian/${{ matrix.release }}:${{ matrix.variant }}"
        '
    - name: "publish"
      run: |
        docker login --username szubersk --password "${{ secrets.GHCR }}" ghcr.io
        docker push "ghcr.io/szubersk/debian/${{ matrix.release }}:${{ matrix.variant }}"
